<%- groups ||= [] -%>
[<%= namespace %>.tls]
type = "table"
category = "TLS"
common = false
groups = <%= groups.to_toml %>
description = "Configures the TLS options for connections from this sink."

<%- if can_enable -%>
[<%= namespace %>.tls.children.enabled]
type = "bool"
common = true
default = false
groups = <%= groups.to_toml %>
sort = 1
description = "Enable TLS during connections to the remote."
<%- end -%>

<%= render("_partials/fields/_tls_common.toml", mode: "connection", namespace: namespace, groups: groups, relevant: "") %>

<%- if can_verify_certificate -%>
[<%= namespace %>.tls.children.verify_certificate]
type = "bool"
default = true
groups = <%= groups.to_toml %>
description = """\
If `true` (the default), Vector will validate the TLS certificate of the \
remote host. Do NOT set this to `false` unless you understand the risks of not \
verifying the remote certificate.\
"""
<%- end -%>

<%- if can_verify_hostname -%>
[<%= namespace %>.tls.children.verify_hostname]
type = "bool"
default = true
groups = <%= groups.to_toml %>
description = """\
If `true` (the default), Vector will validate the configured remote host name \
against the remote host's TLS certificate. Do NOT set this to `false` unless \
you understand the risks of not verifying the remote hostname.\
"""
<%- end -%>
