<%- groups ||= [] -%>
[<%= namespace %>.tls]
type = "table"
category = "TLS"
common = false
groups = <%= groups.to_toml %>
<%= relevant %>
description = "Configures the TLS options for connections from this source."

[<%= namespace %>.tls.children.enabled]
type = "bool"
common = true
default = false
groups = <%= groups.to_toml %>
required = false
<%= relevant %>
description = """\
Require TLS for incoming connections. \
If this is set, an identity certificate is also required.\
"""

<%= render("_partials/fields/_tls_common.toml", mode: "server", namespace: namespace, groups: groups, relevant: relevant) %>

[<%= namespace %>.tls.children.verify_certificate]
type = "bool"
default = false
groups = <%= groups.to_toml %>
<%= relevant %>
description = """\
If `true`, Vector will require a TLS certificate from the connecting host \
and terminate the connection if it is not valid. \
If `false` (the default), Vector will ignore the presence of a client \
certificate.\
"""
